CREATE DATABASE IF NOT EXISTS lab_mysql;
USE lab_mysql;

-- TABLA CARS
DROP TABLE IF EXISTS Cars;
CREATE TABLE Cars (
    VIN VARCHAR(20) NOT NULL, # AQUI NO SE USA INCREMENT POR QUE AUNQUE SEA LA PRIMARY KEY NO ES INT
    manufacturer VARCHAR(50) NOT NULL,
    model VARCHAR(50) NOT NULL,
    year INT NOT NULL,
    color VARCHAR(30) NOT NULL,
    PRIMARY KEY (VIN) # 1 POR TABLA
);

-- TABLA CUSTOMERS
DROP TABLE IF EXISTS Customers;
CREATE TABLE Customers (
    customer_ID INT AUTO_INCREMENT NOT NULL, # SOLO SE USA EN LA QUE VA A SER PRIMARY KEY Y INTEGUER
    name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    email VARCHAR(100) NULL,
    address VARCHAR(100) NOT NULL,
    city VARCHAR(50) NOT NULL,
    state_province VARCHAR(50) NOT NULL,
    country VARCHAR(50) NOT NULL,
    zip_postal_code VARCHAR(100) NOT NULL,
    PRIMARY KEY (customer_ID) # 1 POR TABLA
);

-- TABLA SALESPERSONS
DROP TABLE IF EXISTS Salespersons;
CREATE TABLE Salespersons (
    staff_ID INT AUTO_INCREMENT NOT NULL, # SOLO SE USA EN LA QUE VA A SER PRIMARY KEY
    name VARCHAR(100) NOT NULL,
    store VARCHAR(100) NOT NULL,
    PRIMARY KEY (staff_ID) # 1 POR TABLA
);

-- TABLA INVOICES
DROP TABLE IF EXISTS Invoices;
CREATE TABLE Invoices (
    invoice_number INT AUTO_INCREMENT NOT NULL, # SOLO SE USA EN LA QUE VA A SER PRIMARY KEY
    date DATETIME NOT NULL,
    car_VIN VARCHAR(20) NOT NULL,
    customer_ID INT NOT NULL,
    staff_ID INT NOT NULL,
    PRIMARY KEY (invoice_number), # 1 POR TABLA
    FOREIGN KEY (car_VIN) REFERENCES Cars(VIN),
    FOREIGN KEY (customer_ID) REFERENCES Customers(customer_ID),
    FOREIGN KEY (staff_ID) REFERENCES Salespersons(staff_ID)
);
